    <link rel="stylesheet" href="content/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mochiy+Pop+P+One&amp;subset=japanese&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,700&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Slab:300,400&amp;display=swap">
    <link rel="stylesheet" href="content/assets/css/F19537---MySkills.css">
    <link rel="stylesheet" href="content/assets/css/Footer-Dark-icons.css">
    <link rel="stylesheet" href="https://daneden.github.io/animate.css/animate.min.css">
    <link rel="stylesheet" href="content/assets/css/Lightbox-Gallery-baguetteBox.min.css">
    <link rel="stylesheet" href="content/assets/css/Projects-Grid-Horizontal-images.css">
    <link rel="stylesheet" href="content/assets/css/responsive-blog-card-slider.css">
    <link rel="stylesheet" href="content/assets/css/Responsive-Image-Grid.css">
    <link rel="stylesheet" href="content/assets/css/Skill-Item-skill.css">
    <link rel="stylesheet" href="content/assets/css/Skill-Item.css">
    <link rel="stylesheet" href="content/assets/css/sticky-dark-top-nav-with-dropdown.css">